### ISSUE TITLE
Unrecognized function or variable 'EDPFLinesmex'.

### ISSUE THREAD

**Issue by surya-ceremorphic** [bbenligiray/lens-distortion-rectification#3]
Hi @bbenligiray ,

getting this error when running. Can you please suggest a fix?

![image](https://user-images.githubusercontent.com/109139781/180207219-cb22975b-f40d-4a7b-9d10-43e1eb512456.png)

**Comment by bbenligiray** [comment]
Do you have the `EDPFLinesmex.mexw64` file (from this repo) in the same directory as the `.m` file?

**Comment by surya-ceremorphic** [comment]
> Do you have the `EDPFLinesmex.mexw64` file (from this repo) in the same directory as the `.m` file?

Yes @bbenligiray.

![image](https://user-images.githubusercontent.com/109139781/180712971-f12d5cae-c66c-49ea-95cd-63aa145ee871.png)

**Comment by bbenligiray** [comment]
Are you on Windows? Because mexw64 files are built for Windows and unfortunately I don't have the source files around.

**Comment by surya-ceremorphic** [comment]
> Are you on Windows? Because mexw64 files are built for Windows and unfortunately I don't have the source files around.

I am running it in online MATLAB. I think I should be downloading MATLAB software.
